### ISSUE TITLE
Enable debugging mode

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#101]
Currently, the Slack app is not in debugging mode when running locally. As such, every time the app needs to be restarted when some code change is made. It may be worthwhile to add an environment variable for whether enabling the debugging model with `debug=True` when starting the flask app

https://github.com/Aggregate-Intellect/sherpa/blob/6671d2699bf0002fb85ebaa36ebd834438a66de0/apps/slackbot/bolt_app.py#L133

**Comment by oshoma** [comment]
@20001LastOrder I can take a crack at this.

**Comment by oshoma** [comment]
@20001LastOrder the PR is ready for your review.
