### ISSUE TITLE
[BUG]  Error handling

### ISSUE THREAD

**Issue by Eyobyb** [Aggregate-Intellect/sherpa#105]
**Describe the bug**
If the system has any error or crashes there is no way of mentioning it to the slack user.

**To Reproduce**
since the system should handle any error.  you can text by causing syntax error or referential error inside the mention endpoint

**Expected behavior**
If there is an error the system should catch that error and respond with a generic message mentioning the existence 
of an issue and that we couldn't handle their request now

**Comment by amirfz** [comment]
@20001LastOrder @YujingYang666777 could you please provide a list of the python code exceptions we are currently handling? and what the behavior of the system is when we face them?

@saminegash could you please provide a list of deployment related issues we are currently handling and how the system handles them?
