### ISSUE TITLE
Suggestion: setting LLM model temperature = 0

### ISSUE THREAD

**Issue by johnnykfeng** [Aggregate-Intellect/sherpa#110]
I notice that we are using default `temperature=0.7` when initializing our LLM calls, - see `task_agent.py` under `def run()`. I propose to set `temperature=0` for all LLM models in the code, rather than leave it as default. 

Low temperature gives more deterministic and less random output. It is generally good practice, especially when we are using the LLM to output precise JSON formats. Here is a guide explains the effect of temperature very well, https://community.openai.com/t/cheat-sheet-mastering-temperature-and-top-p-in-chatgpt-api-a-few-tips-and-tricks-on-controlling-the-creativity-deterministic-output-of-prompt-responses/172683

This may help with the repeating command problem in issue #18

**Comment by 20001LastOrder** [comment]
Agreed, we should make this as a configurable parameter

**Comment by amirfz** [comment]
@20001LastOrder is this a quick change?

**Comment by amirfz** [comment]
addressed in #131
