### ISSUE TITLE
Test cases for existing features

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#113]
**PROBLEM**
The project is speeding up as the number of new PRs is increasing. We need a way to make sure these PRs will not break existing changes.

**SOLUTION**
Since the project is already configured with pytest, we should implement some minimal automated unit/integration tests for existing features and the end-to-end flow.

**Comment by oshoma** [comment]
Next steps: 
- use `pytest-cov` to measure existing level of test coverage
- identify features that have no test coverage at all 
- post a list here suggesting which features need tests to be written

**Comment by 20001LastOrder** [comment]
Closed by https://github.com/Aggregate-Intellect/sherpa/pull/164
