### ISSUE TITLE
[BUG] No prompt size check causing errors

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#115]
**Describe the bug**
The duplicated command check is formatting a prompt with previous messages but it is not bounded by prompt size, causing potential prompt size error.

**To Reproduce**
1. Run the backend and connect it to the slack app
2. In the slack channel with the slack bot, send the following message: `@Sherpa
 how many Grand Slam does Carlos Alcaraz has`

**Expected behavior**
A response is given by Sherpa

**Screenshots**
![image](https://github.com/Aggregate-Intellect/sherpa/assets/25534730/18300b71-01db-4575-9de7-72ce8f0f2868)

**Comment by 20001LastOrder** [comment]
I’ll work on this today

**Comment by 20001LastOrder** [comment]
Oh, OK, I'll check with her. Should we disable the duplicated action check for now? @amirfz

**Comment by amirfz** [comment]
hmm not sure. perhaps check with her and decide accordingly

**Comment by 20001LastOrder** [comment]
Fixed by #122
