### ISSUE TITLE
[BUG] Different responses for the same prompt

### ISSUE THREAD

**Issue by johnnykfeng** [Aggregate-Intellect/sherpa#124]
**Describe the bug**
Same question would yield different response. Sometimes, the response is not well formatted.
First response seems like an error. Second response was okay. Third response was different but seems correct. 

**To Reproduce**
prompt `@Sherpa how many countries are there` 3 times

**Expected behavior**
Should all be the same response.

**Screenshots**
1)
![image](https://github.com/Aggregate-Intellect/sherpa/assets/38768263/06ba03fa-4072-42a9-8f8a-a76df4f63a88)
2)
![image](https://github.com/Aggregate-Intellect/sherpa/assets/38768263/744e08ad-3844-41c2-bbe8-36eadef3e7e7)
3)
![image](https://github.com/Aggregate-Intellect/sherpa/assets/38768263/93796136-beb0-40a4-9b4a-7a634b714d70)

**Environment**
I did this in my local testing environment, it doesn't have access to the same vector db as the deployed version, so context search doesn't work. Regardless, responses should be the same.

**Additional context**
This may be related to issue #110

**Comment by 20001LastOrder** [comment]
Yes, this is related to the temperature of the model in #110

**Comment by amirfz** [comment]
addressed in #131  and later refactored through config.py in slack app folder
