### ISSUE TITLE
[open book] add paper links to the open book "journal club" summaries

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/sherpa#130]
**Problem**
Currently the open book "journal club" section only has summaries of the sessions. I'm not sure how valuable that is.

**Solution**
Need to find a way to enrich that section with more useful information, like paper / repo links, wihtout adding too much operational overhead

**Comment by oshoma** [comment]
@amirfz does a solution here require manual writing and editing, or were you thinking about an automated solution like Sherpa providing citations (for example)?

**Comment by amirfz** [comment]
this is a manual task. I'll need to find a bunch of free time and do this.
it is not urgent at all though. we have also stopped adding journal club
summaries to the book. so this might not even be relevant any more.
