### ISSUE TITLE
[FEATURE] Decompose complex and procedural questions into smaller tasks

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/sherpa#153]
**PROBLEM**
Currently the QA agent just starts trying things out without "thinking". This runs into problems like repeated actions, agent not decomposing the problem into subtasks properly etc. 

**SOLUTION**
it might be helpful to ask it to provide a step by step plan first, and then for each step decide on an action (tool + query), and keep track of all necessary actions until they are done. this might be more constructive way to handle more complex and procedural questions. 

It will be helpful to know what types of questions need decomposition, and use it only when needed based on some heuristics or LLM calls. 

**ALTERNATIVES**
- one alternative is to provide problem solving recipes explicitly (like CoT type of examples) in a few shot setup

**OTHER INFO**
n/a

**Comment by 20001LastOrder** [comment]
Closed by https://github.com/Aggregate-Intellect/sherpa/pull/198
