### ISSUE TITLE
[FEATURE] Refactor Context Search Tool into session history retrieval + document retrieval tools

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#154]
**PROBLEM**
Currently the description of the context search is not explicit on what information is stored there. 

**SOLUTION**
There are two solutions: 
1. Add description on different dataset we stored in the vector db
2. Break the context search into multiple tools, one for each dataset/domain 

**ALTERNATIVES**
Describe alternatives you've considered

**OTHER INFO**

**Comment by amirfz** [comment]
Context Search has to be split into a few parts:
- Context Search that only deals with the session history
- Other tools that deal with document retrieval from the vector db

**Comment by 20001LastOrder** [comment]
Closed as it evolves into the Share Memory in Sherpa
