### ISSUE TITLE
[BUG] Incorrect URL format in citation reference

### ISSUE THREAD

**Issue by YujingYang666777** [Aggregate-Intellect/sherpa#155]
**Describe the bug**
After asking the question, sherpa provides a solution with a reference. However, the reference does not follow the desired format.

**To Reproduce**
This bug randomly appears. Asking the same question may not get the same result.

**Expected behavior**
We expect a number and URL in the reference.

**Screenshots**
here is the returned result:
Please refer to the Langchain documentation for more detailed information and examples on using Langchain with SQL databases. [[1]](http://python.langchain.com/en/latest/modules/chains/examples/sqlite.html)
[[1]](http://python.langchain.com/en/latest/modules/chains/examples/sqlite.html) SQL Chain example [DocID:1]

Note: it should not have " [DocID:1]" within the reference

**Environment**
development environment in the main branch

**Additional context**

**Comment by 20001LastOrder** [comment]
Closed by https://github.com/Aggregate-Intellect/sherpa/pull/241
