### ISSUE TITLE
[FEATURE] Integrate testing docs into "How To" section of ReadTheDocs

### ISSUE THREAD

**Issue by oshoma** [Aggregate-Intellect/sherpa#205]
**PROBLEM**
@Eyobyb created some good first draft test documentation in #f39049.
However when you navigate to https://sherpa-ai.readthedocs.io/en/latest/How_To/index.html 
the docs are not integrated there, so they aren't discoverable. 

**SOLUTION**
Add the test docs as a page discoverable from the How To index.

**ALTERNATIVES**

**OTHER INFO**

**Comment by oshoma** [comment]
@amirfz could you please take a look? I believe you know the most about Sphinx docs.

**Comment by amirfz** [comment]
I think it's a configuration problem. I sent a note to Percy about how it
can be fixed. I'm currently having an issue with git and might take me a
while to find time to figure it out. but hopefully this blog post can
resolve it

https://blog.readthedocs.com/migrate-configuration-v2/

if anyone else wants to take a stab at it, feel free to do so too
