### ISSUE TITLE
[Test Error] ModuleNotFoundError: No module named 'sherpa_ai.agents.programmer'

### ISSUE THREAD

**Issue by oshoma** [Aggregate-Intellect/sherpa#215]
tests/unit_tests/test_planner.py fails trying to import `sherpa_ai.agents.programmer` , a module which does not exist.

**To Reproduce**
```
cd src

make test

ImportError while importing test module '/Users/oshoma/dev/sherpa/src/tests/unit_tests/test_planner.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../miniconda3/envs/sherpa-slackbot/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit_tests/test_planner.py:7: in <module>
    from sherpa_ai.agents.programmer import Programmer
E   ModuleNotFoundError: No module named 'sherpa_ai.agents.programmer'
```

**Expected behavior**
Test should run cleanly.

**Additional context**
I'm guessing there was previously a module `sherpa_ai.agents.programmer` and this test started failing after that module was deleted. I'm not sure what the plan is, e.g. will there be a "programmer" module or not?

**Comment by ChenKua** [comment]
"I'm guessing there was previously a module sherpa_ai.agents.programmer and this test started failing after that module was deleted. " Yes, you are right.
For now, I don't think we still need a programmer module. We should modify the test accordingly.
