### ISSUE TITLE
Add Follow-up Question Tool

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/sherpa#22]
Sometimes the question asked does not have enough context. the assistant should be able to recognize that and ask clarification questions. 

assignee: Karim

**Comment by hakeemo** [comment]
Working on this. Using React Framework we should be able to implement this.

**Comment by hakeemo** [comment]
@20001LastOrder . Isn't this just this tool here? 

https://github.com/Aggregate-Intellect/sherpa/blob/24827f2b7435f149874d2335d744fb5c2bf661d5/apps/slackbot/tools.py#L125

**Comment by amirfz** [comment]
@hakeemo any updates on this?
