### ISSUE TITLE
[BUG] Github Readme extractor not working

### ISSUE THREAD

**Issue by Eyobyb** [Aggregate-Intellect/sherpa#232]
**Describe the bug**
The GitHub readme extractor is not functioning. 
It will fail to extract the GitHub readme of a given link. 
[https://github.com/Aggregate-Intellect/sherpa/blob/main/src/sherpa_ai/scrape/extract_github_readme.py](https://github.com/Aggregate-Intellect/sherpa/blob/main/src/sherpa_ai/scrape/extract_github_readme.py)

**To Reproduce**
ask a question by providing a GitHub link 
eg. What information is being discussed in the link "https://github.com/Aggregate-Intellect/sherpa"?

**Expected behavior**
should scrape the readme from the given GitHub link and pass the readme as a context.

**Additional context**
- With my initial observation, I noticed it failed to contact GitHub API. check the token also the request header as a whole.
- It also should pass the test [https://github.com/Aggregate-Intellect/sherpa/blob/main/src/tests/unit_tests/scrape/test_extract_github_readme.py](https://github.com/Aggregate-Intellect/sherpa/blob/main/src/tests/unit_tests/scrape/test_extract_github_readme.py)

**Comment by 20001LastOrder** [comment]
Closed by #244
