### ISSUE TITLE
Project Mgmt: Send Github notifications to Slack #sherpa-dev

### ISSUE THREAD

**Issue by oshoma** [Aggregate-Intellect/sherpa#240]

**Comment by oshoma** [comment]
## Opportunity
It would be helpful to automatically send Slack messages to inform Sherpa contributors of important Github events in the #sherpa-dev channel. E.g. a PR was submitted and needs review; and important actions taken, e.g. "Percy merged PR211 into main, closing issue https://github.com/Aggregate-Intellect/sherpa/issues/10".

## Solution
Add the integration to Slack: https://slack.github.com/ .

This needs to be done by someone with both Github and Slack admin permissions.

**Comment by oshoma** [comment]
@20001LastOrder and @amirfz is one of you able to do this for us?

**Comment by oshoma** [comment]
I added the github integration to Aggregate Intellect Slack in a new channel. Let's see how it goes.

**Comment by amirfz** [comment]
noice! we had something like this but we disabled it back when the free
slack was limited by the number of messages (instead of the current setup:
days)
