### ISSUE TITLE
[BUG] Poetry install does not install all dependencies

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#247]
**Describe the bug**
Currently, if you have a clean Python environment, run `poetry install` to install the dependencies, it would miss the following dependencies
* LangChain
* boto3
* transformers

We should investigate this soon because I'm afraid this may be influencing the deployment as well.

**To Reproduce**
1. Create a new python environment
2. Run `poetry install` for the project
3. Run `pytest .`

**Expected behavior**
The test will run and show both passing and failed tests

**Actual behavior**
The test run fails with error about missing dependency

**Comment by oshoma** [comment]
@20001LastOrder is this working now? I know you checked in a fix for transformers. Not sure about the other 2.
