### ISSUE TITLE
[BUG] Verbose mode is not default

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#248]
**Describe the bug**
Currently, Sherpa is not running in the `verbose` mode by default.

**Expected behavior**
Sherpa would run in the `verbose` mode by default and provide details on the task execution

**Comment by oshoma** [comment]
@20001LastOrder do you mean 1) when Sherpa is run in a production environment it should start in verbose mode?  Or 2) when run in any environment Sherpa should always default to verbose mode?

**Comment by amirfz** [comment]
this is actually a request from me. currently sherpa slack doesn't show its
"reasoning process" and provides an answer "out of nowhere". this makes it
hard to superficially debug when things go wrong, or more importantly to
trust "its work" when some answer is provided that might need further
investigation. the idea is to make what is currently available via
`--verbose` flag as the default behavior. now is it just for slack, or
general behavior of the library is a good design question. can it be done
as a flag which is turned on for slack sherpa in prod, and turned off in
contexts where only the "answer" is relevant?

in general though, this is in the broader context of having sherpa
communicate its reasoning steps or errors to the end user and providing
guidance about how things can be resolved. so ideally we need a framework
and set of design choices that allow sherpa interact effectively with end
user with some UX choices that can be configured based on context.
