### ISSUE TITLE
[BUG] Test failure in test_extract_github_readme_with_valid_url_succeeds

### ISSUE THREAD

**Issue by oshoma** [Aggregate-Intellect/sherpa#252]
**Describe the bug**
This test is failing on my machine and for @20001LastOrder as well.

**To Reproduce**

1. cd src
2. pytest tests
3. Observe error as follows:

```
___________________________________________________________ test_extract_github_readme_with_valid_url_succeeds ___________________________________________________________

    def test_extract_github_readme_with_valid_url_succeeds():
        repo_url = "https://github.com/Aggregate-Intellect/sherpa"
>       content = extract_github_readme(repo_url)

tests/unit_tests/scrape/test_extract_github_readme.py:6: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
sherpa_ai/scrape/extract_github_readme.py:36: in extract_github_readme
    matching_files = [
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <dict_keyiterator object at 0x7fbe5457a8b0>

    matching_files = [
        file["name"]
        for file in files
        if (
            (
>               file["name"].lower().endswith(".md")
                or file["name"].lower().endswith(".rst")
            )
            and file["name"].lower().startswith("readme")
        )
    ]
E   TypeError: string indices must be integers

sherpa_ai/scrape/extract_github_readme.py:41: TypeError
-------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------
2023-12-06 12:26:30.282 | INFO     | sherpa_ai.scrape.extract_github_readme:extract_github_readme:26 - None
```

**Expected behavior**
The test should succeed.

**Environment**
When I do not have a `GITHUB_AUTH_TOKEN` in my environment file this test fails because it requires a valid GITHUB_AUTH_TOKEN. You can see this in the test output by adding a `print(files)` statement at line 41. Here's what I get:

```
{'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}
```

I notice the test also depends on OPENAI and PineCone. When I don't have these set up, the test fails.

Let's modify the tests so that they work in offline mode, like we recently did for the tests depending on LLMs.

**Next steps**

1. Modify `extract_github_readme`to log a warning and then fail gracefully by returning None, instead of throwing an exception when `GITHUB_AUTH_TOKEN` is undefined.
2. In `extract_github_readme`, there are two groups of lines that access json data with Try/Except. Wrap these lines with Try/Except to handle the error case where the json data doesn't parse as expected. This will happen, for example, when a github auth token expires.  You can mock the github response to test the try/except.
3. Modify `save_to_pine_cone` to log a warning and fail gracefully (suggestion: return False) when `PINECONE_ENV` or `OPENAI_API_KEY` is undefined.
4. Modify the two existing tests in `test_extract_github_readme.py` so that they work in both offline mode and online mode. See https://sherpa-ai.readthedocs.io/en/latest/How_To/Test/test.html#offline-and-online-testing for instructions on how to do make the tests work both online and offline. In offline mode the tests should use mocks so that they work even when the necessary ENV variables are undefined. In online mode the tests should fail if the necessary ENV variables are undefined. 

If the work for part 4 is large then it would make sense to do steps 1-3 as a single PR and step 4 as its own separate PR.

**Comment by 20001LastOrder** [comment]
Fixed by #228
