### ISSUE TITLE
[BUG] Cannot set attribute in Pinecone Vector Store

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#256]
**Describe the bug**
The `vectorstore` based on Pinecone will fail due to `cannot set attribute` error

**To Reproduce**
1. Add Pinecone related keys to the `.env` file
2. Run `pytest` in the `src` folder
3. Multiple tests will fail due to the following error

```
    def __init__(self, namespace, db, embeddings, text_key):
        self.db = db
        self.namespace = namespace
>       self.embeddings = embeddings
E       AttributeError: can't set attribute

sherpa_ai\connectors\vectorstores.py:24: AttributeError
```

**Expected behavior**
These tests should pass

**Screenshots**
![image](https://github.com/Aggregate-Intellect/sherpa/assets/25534730/b5976dcc-252b-4058-8c04-35bff3171384)

**Additional context**
After a bit dig in, I found that `LangChain` updated their `VectorStore` API and now embedding is a property function as following
``` python
 @property
    def embeddings(self) -> Optional[Embeddings]:
        """Access the query embedding object if available."""
        logger.debug(
            f"{Embeddings.__name__} is not implemented for {self.__class__.__name__}"
        )
        return None
```

So we need to change our inheritance accordingly, maybe by overriding this function.

**Comment by oshoma** [comment]
OK. The bug and failing test are unrelated to this PR, then?

**Comment by 20001LastOrder** [comment]
> OK. The bug and failing test are unrelated to this PR, then?

Yes, and it will be solved separately.

**Comment by oshoma** [comment]
Ok great. The rest of my comments are about small things.
