### ISSUE TITLE
Scraping the Content of URLs from Certain Slack Channels

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/sherpa#26]
this is to keep the content of the knowledgebase up to date

**Comment by amirfz** [comment]
this is put on hold in favor of #27 as a temp solution

**Comment by oshoma** [comment]
@amirfz can you please review this issue? I can't tell if it's already resolved. If we still need it, please add a description so others know what it is about and the next steps.

**Comment by amirfz** [comment]
the idea was to scrape the papers posted in the "resources" channel into
our vector db but since then we have decided that "google search" provides
enough info for demo purposes and we don't need anything more complex for
the slack sherpa. so we can close this for the time being

**Comment by oshoma** [comment]
Thanks @amirfz I will close this.
