### ISSUE TITLE
[OPS] Project priorities aren't apparent to Sherpa community

### ISSUE THREAD

**Issue by oshoma** [Aggregate-Intellect/sherpa#264]
**PROBLEM**
For a newcomer to Sherpa, it isn't immediately apparent what the project priorities are. What sort of stuff is valuable to work on, and what is not valuable?

**SOLUTION**
Post project priorities somewhere easily discoverable to give people a better sense of where we are headed.
Options:

1. Sherpa README
2. Slack #sherpa-dev channel  -- post and pin

**Comment by 20001LastOrder** [comment]
We are shifting focus to use case-based projects for community involvement. And this release map helps planning on upcoming features: https://drive.google.com/file/d/1Ccn9mC5IgcS9wzXc8u9z4GwvOUiAgpuW/view?usp=sharing
