### ISSUE TITLE
Handling the Inline URL Edge Case

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/sherpa#27]
Handle the case where the user pastes a URL and asks a question about that resource

assignee: Eyob

**Comment by amirfz** [comment]
@Eyobyb is working on this

**Comment by Eyobyb** [comment]
I resolved the issue by locating links in the question, and recreating the question to include the scraped and summarized content from the links.

**Comment by Eyobyb** [comment]
PR for the fix https://github.com/Aggregate-Intellect/practical-llms/pull/50
