### ISSUE TITLE
[FEATURE] QA transcript summarization

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/sherpa#271]
**PROBLEM**
we are using a structured summarization script to turn the transcripts of the workshop sessions into summaries that we attach to the open book as well youtube videos, social posts, etc. the summary often misses lots of interesting nuances discused during the QA at the end of the presentations. 
ref: https://github.com/Aggregate-Intellect/sherpa/blob/main/scripts/transcript_summarizer_aws_lambda.py

**SOLUTION**
Add a secondary summarizer that specifically only receives the QA part of the transcripts, and specifically summarizes each question and the corresponding answer and maintains the QA structure. 

**ALTERNATIVES**
n/a

**OTHER INFO**
Amir can provide sample data for this.

**Comment by code-mango** [comment]
I'm working on implementing this script.
