### ISSUE TITLE
Create an LLM selection tool

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/sherpa#29]
the question of what LLM to choose is huge without any good answers. we should research and create a tool that can answer this question well.

**Comment by amirfz** [comment]
most other projects use promp engineering to select the tool. we could consider modularize the "agent" to controller (action planner), tool, reflection, etc modules

**Comment by oshoma** [comment]
@amirfz can we close this as a dup of #36 ?

**Comment by amirfz** [comment]
this is actually a duplicte (or subset of) #246  and #64 . the broad idea was to have a tool that QA agent can use specifically to answer what llm to use for what. this is different than #36 which is focused on helping Agents choose tools in general.

**Comment by 20001LastOrder** [comment]
Closed as it's duplicated #246 and #64
