### ISSUE TITLE
[BUG] Error when tagging Sherpa due to spaCy trained pipeline for English not being installed

### ISSUE THREAD

**Issue by artificialfintelligence** [Aggregate-Intellect/sherpa#332]
**Describe the bug**
Manual installation instructions and Dockerfile are missing a newly required step: Downloading the spaCy trained pipeline for English.

**To Reproduce**
1. Perform a fresh installation of Sherpa following the directions [here](https://sherpa-ai.readthedocs.io/en/latest/How_To/Slack%20Bot/2_run_slackbot.html) or a fresh redeployment of the docker container.
2. When you tag the Sherpa slack bot, it fails with the following error message in the console:
```
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
```
Also in Slack, you get the following error:
![image](https://github.com/Aggregate-Intellect/sherpa/assets/31551629/0e9a0a48-aba8-42c9-84c9-b247a20081a0)

**Additional context**
The culprit is PR #273, specifically [this commit](https://github.com/Aggregate-Intellect/sherpa/pull/273/commits/47c535fd65835bafad77ac9905fce6f2c7384cd5).  
It is easily fixed by performing the following command (to be added to the manual installation instructions, as well as, more importantly, the Dockerfile):
```
python -m spacy download en_core_web_sm
```

**Comment by artificialfintelligence** [comment]
@20001LastOrder I ran this by @Eyobyb and created a [PR with the fix](https://github.com/Aggregate-Intellect/sherpa/pull/333)

**Comment by 20001LastOrder** [comment]
Fixed by https://github.com/Aggregate-Intellect/sherpa/pull/333
