### ISSUE TITLE
sherpa produces reasonable answers but cites incorrect resources

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/sherpa#34]
example:

Tree of thought and reflection are different in their approaches to generating output. Tree of thought focuses on exploring multiple branches or alternative paths of reasoning, allowing for diverse and creative outputs. It captures a wider range of solutions by considering different possibilities. On the other hand, reflection involves thinking back on previous actions or experiences to gain insight or improve performance. It is a self-critical process that aims to refine one's approach based on past decisions and strategies. While tree of thought focuses on generating alternative outputs, reflection focuses on self-improvement and learning.
Source: [Chain of Thought: An Improved Beam Search Strategy](https://arxiv.org/pdf/1610.02424.pdf), [Tree of Thoughts: Universal Sentence Representations as Logical Entailments](https://arxiv.org/pdf/1803.05407.pdf)

the first URL is correct but the name of the paper is incorrect, and also the answer is not quite related to that paper

**Comment by bharatji30** [comment]
i will look at this one. starting with issue recreation.

**Comment by bharatji30** [comment]
@amirfz  Do you know the prompt which generated this response?

**Comment by amirfz** [comment]
could you check the source code? I'm not sure
