### ISSUE TITLE
[BUG] Action selection does not take the action description into consideration

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#359]
**Describe the bug**
Currently, the action string used for action selection does not take the description of an action into consideration:

https://github.com/Aggregate-Intellect/sherpa/blob/a115d64cdf556d4d3b740927a71775047f218973/src/sherpa_ai/actions/base.py#L20-L26

**Expected behavior**
The description should be included in the `__str__` function of the action.

**Comment by Bubbletea98** [comment]
I will look into this :)
