### ISSUE TITLE
Better Tool Selection

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#36]
### Description:

Currently, the system selects the next tool to use based on the tool name and a short description. However, with the number of tools increasing, it is unknow that whether the system choose the tool randomly or though some reasoning. 

### Steps to Reproduce:

Check the [tools.py](https://github.com/Aggregate-Intellect/practical-llms/blob/main/apps/slackbot/tools.py) file, notice that there is only the name of the tool and a short description. 

**Observation**: Some experiments are necessary to study more about how the system chooses the next tool. And then a better way should be proposed for tool selection. 

### Possible Solutions:

In addition to the name and description of the tool, we should also add some input/output examples to the tool to make sure the system can understand the usage of the tool. 

### Steps Taken So Far:

N/A.

### Environment:

N/A.

**Comment by amirfz** [comment]
Percy is working on this and will raise a PR after fixing some issues with the qualtiy of tool selection

**Comment by amirfz** [comment]
could we use [this](https://python.langchain.com/docs/modules/agents/how_to/custom_agent_with_tool_retrieval)?
