### ISSUE TITLE
[FEATURE] Reranking of the Search Results

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#362]
**PROBLEM**
Currently, the search actions simply use the underlying search engine to retrieve results from the (refactored query). We may also want to do a reranking based on the original question. 

**SOLUTION**
After the BaseRetrievalAction is implemented (https://github.com/Aggregate-Intellect/sherpa/issues/347), add a reranking component to it.

**Comment by andytai7** [comment]
Will look into this.
