### ISSUE TITLE
[FEATURE] Blog writer - Bring the user into the loop

### ISSUE THREAD

**Issue by KulwantSinghYadav** [Aggregate-Intellect/sherpa#378]
**PROBLEM**
In the Blog writer app, user has no ability or control over the blog being generated. 

**SOLUTION**
Set up the @user as an independent agent. After every paragraph generation, this agent asks if user wants any changes in the blog. 
- If no changes are needed, simply type yes or y and enter.
- If changes are needed, write instructions and press enter

**Comment by 20001LastOrder** [comment]
Before closing this issue, I'm thinking if any of you can introduce this new functionality in the tutorial document: https://github.com/Aggregate-Intellect/sherpa/blob/main/docs/How_To/Tutorials/blog_writer.rst @KulwantSinghYadav @artificialfintelligence . Thanks!

**Comment by KulwantSinghYadav** [comment]
@artificialfintelligence thank you!

**Comment by artificialfintelligence** [comment]
@20001LastOrder Done. It's a very minimal change though.
