### ISSUE TITLE
[FEATURE] Map user input into action / path and input

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#399]
### Description
With the flow policy (https://github.com/Aggregate-Intellect/sherpa/issues/398), there will be two kinds of nodes require human input
1. For certain action nodes, a human input is necessary (e.g. read a file)
2. For certain decision nodes, the path will selected based on human input

For each of them, we want to enable the user to input in action nature language text and then map the text into action input or path/action selection. 

### Basic Design
![image](https://github.com/Aggregate-Intellect/sherpa/assets/25534730/bfb11b9e-368d-4ac4-a4c9-1762e1d0cc23)

**Comment by 20001LastOrder** [comment]
@Bubbletea98 

cc. @amirfz Could you take a look at the description and see if it makes sense?

**Comment by amirfz** [comment]
@20001LastOrder @Bubbletea98 mm I am not 100% sure we're on the same page, so to help the conversation I put together this sample conversation. please take a look and let's have a discussion; https://docs.google.com/document/d/1wLFFoJu_Fz5GPlwInOYM5yCWFvjnhIdVOii66Kq4oSY/edit

**Comment by amirfz** [comment]
ok great. I'll take a look. I asked the blog group to create a few similar
ones so that we can compare and contrast
