### ISSUE TITLE
[FEATURE] Chained Actions

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#418]
**PROBLEM**
Currently, actions in Sherpa cannot be chained together to create a _composite chained action_. This functionality can come in handy when one needs to combine multiple actions to create a new action. I'm considering the following
1. Each action in the chained action can be a singular action or again another atomic action
2. Each action's input can either rely on the input when executing the action or the output of a previous action.
3. The argument when executing this chained action can be automatically calculated by examining the dependency at 2

**Comment by Bubbletea98** [comment]
I can work on it, will try to finish it by the end of next week.
