### ISSUE TITLE
Namespace for Pinecone Database is Hard-Coded

### ISSUE THREAD

**Issue by 20001LastOrder** [Aggregate-Intellect/sherpa#48]
### Description:
Currently, when the database is set to *Pinecone* by providing the Pinecone API key in the `.env` file, the namespace used in the search is hard-coded to `ReadTheDoc`. (See the code [here](https://github.com/Aggregate-Intellect/practical-llms/blob/f539c84f9e61c136f80d08ffb0b3085072017d01/apps/slackbot/bolt_app.py#L172)). This may cause future problems if we change the namespace or use multiple namespaces and so on. 

### Possible Solution:
I think the simple solution would be just to add another environment variable to the `.env` file and access it to get the namespace.

As the project is gaining complexity and the configuration becomes increasingly complex as well, we may also want to investigate other configuration options than the `.env` file, such as `JSON` or `YAML`

**Comment by oshoma** [comment]
@20001LastOrder I'll work on this, and on cleaning up initialization in general. You can assign to me.

**Comment by oshoma** [comment]
@20001LastOrder related to this, I notice we have both `OPENAI_KEY` and `OPENAI_API_KEY`. Do we need both?

**Comment by oshoma** [comment]
@20001LastOrder this issue should be resolved by #89 . Please review when you have time.
