### ISSUE TITLE
Traditional NLP models Vs. LLM Performance on Tasks

### ISSUE THREAD

**Issue by jiristo** [Aggregate-Intellect/sherpa#49]
https://github.com/Aggregate-Intellect/practical-llms/blob/f1bab969b90288335479d6bef27362d67c78094f/docs/LLM%20Engineering/llms_in_enterprise.rst?plain=1#L24

Based on the recording, I think this is not correct.  Traditional NLP models, as the speaker refers to this paper  https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4337182, may perform better on financial analysis tasks (sentimet).

**Comment by amirfz** [comment]
@jiristo could you PR a correction to that with more info and citations?
