### ISSUE TITLE
refactor code base and remove unused code

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/sherpa#52]

**Comment by oshoma** [comment]
@amirfz do you have any particular changes in mind already? I am going through the code and am happy to suggest some cleanups, but I don't want to step on toes or duplicate work already in progress

**Comment by amirfz** [comment]
@oshoma nothing concrete beyond the overall project structure. so if you have suggestions, please go ahead. if they're small enough, make PRs and if they're bigger and structural I suppose you can create issues to discuss them first?
