### ISSUE TITLE
Serve Llama 2 Model Inference as API (as an alternative to Open AI or for other uses)

### ISSUE THREAD

**Issue by ChenKua** [Aggregate-Intellect/sherpa#81]
Make flask apps for LM we host so that we can inference LLM in restful api. and this will make thing more modularized

**Comment by amirfz** [comment]
we can look into Sage Maker Jumpstart for this

**Comment by ChenKua** [comment]
Not much progress from my side. Hope Karim or Suhas and others have discussed it.

**Comment by 20001LastOrder** [comment]
Closed as not planned
